// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DistSSE.proto

#ifndef PROTOBUF_DistSSE_2eproto__INCLUDED
#define PROTOBUF_DistSSE_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
namespace DistSSE {
class CacheRequestMessage;
class CacheRequestMessageDefaultTypeInternal;
extern CacheRequestMessageDefaultTypeInternal _CacheRequestMessage_default_instance_;
class ExecuteStatus;
class ExecuteStatusDefaultTypeInternal;
extern ExecuteStatusDefaultTypeInternal _ExecuteStatus_default_instance_;
class SearchReply;
class SearchReplyDefaultTypeInternal;
extern SearchReplyDefaultTypeInternal _SearchReply_default_instance_;
class SearchRequestMessage;
class SearchRequestMessageDefaultTypeInternal;
extern SearchRequestMessageDefaultTypeInternal _SearchRequestMessage_default_instance_;
class SetupRequestMessage;
class SetupRequestMessageDefaultTypeInternal;
extern SetupRequestMessageDefaultTypeInternal _SetupRequestMessage_default_instance_;
class UpdateRequestMessage;
class UpdateRequestMessageDefaultTypeInternal;
extern UpdateRequestMessageDefaultTypeInternal _UpdateRequestMessage_default_instance_;
}  // namespace DistSSE
namespace google {
namespace protobuf {
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace protobuf
}  // namespace google

namespace DistSSE {

namespace protobuf_DistSSE_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_DistSSE_2eproto

// ===================================================================

class SetupRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.SetupRequestMessage) */ {
 public:
  SetupRequestMessage();
  virtual ~SetupRequestMessage();

  SetupRequestMessage(const SetupRequestMessage& from);

  inline SetupRequestMessage& operator=(const SetupRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetupRequestMessage& default_instance();

  static inline const SetupRequestMessage* internal_default_instance() {
    return reinterpret_cast<const SetupRequestMessage*>(
               &_SetupRequestMessage_default_instance_);
  }

  void Swap(SetupRequestMessage* other);

  // implements Message ----------------------------------------------

  inline SetupRequestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  SetupRequestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetupRequestMessage& from);
  void MergeFrom(const SetupRequestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetupRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 setup_size = 1;
  void clear_setup_size();
  static const int kSetupSizeFieldNumber = 1;
  ::google::protobuf::uint64 setup_size() const;
  void set_setup_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:DistSSE.SetupRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 setup_size_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.SearchRequestMessage) */ {
 public:
  SearchRequestMessage();
  virtual ~SearchRequestMessage();

  SearchRequestMessage(const SearchRequestMessage& from);

  inline SearchRequestMessage& operator=(const SearchRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchRequestMessage& default_instance();

  static inline const SearchRequestMessage* internal_default_instance() {
    return reinterpret_cast<const SearchRequestMessage*>(
               &_SearchRequestMessage_default_instance_);
  }

  void Swap(SearchRequestMessage* other);

  // implements Message ----------------------------------------------

  inline SearchRequestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  SearchRequestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SearchRequestMessage& from);
  void MergeFrom(const SearchRequestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SearchRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes kw = 1;
  void clear_kw();
  static const int kKwFieldNumber = 1;
  const ::std::string& kw() const;
  void set_kw(const ::std::string& value);
  #if LANG_CXX11
  void set_kw(::std::string&& value);
  #endif
  void set_kw(const char* value);
  void set_kw(const void* value, size_t size);
  ::std::string* mutable_kw();
  ::std::string* release_kw();
  void set_allocated_kw(::std::string* kw);

  // bytes tw = 2;
  void clear_tw();
  static const int kTwFieldNumber = 2;
  const ::std::string& tw() const;
  void set_tw(const ::std::string& value);
  #if LANG_CXX11
  void set_tw(::std::string&& value);
  #endif
  void set_tw(const char* value);
  void set_tw(const void* value, size_t size);
  ::std::string* mutable_tw();
  ::std::string* release_tw();
  void set_allocated_tw(::std::string* tw);

  // uint64 uc = 3;
  void clear_uc();
  static const int kUcFieldNumber = 3;
  ::google::protobuf::uint64 uc() const;
  void set_uc(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:DistSSE.SearchRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr kw_;
  ::google::protobuf::internal::ArenaStringPtr tw_;
  ::google::protobuf::uint64 uc_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SearchReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.SearchReply) */ {
 public:
  SearchReply();
  virtual ~SearchReply();

  SearchReply(const SearchReply& from);

  inline SearchReply& operator=(const SearchReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SearchReply& default_instance();

  static inline const SearchReply* internal_default_instance() {
    return reinterpret_cast<const SearchReply*>(
               &_SearchReply_default_instance_);
  }

  void Swap(SearchReply* other);

  // implements Message ----------------------------------------------

  inline SearchReply* New() const PROTOBUF_FINAL { return New(NULL); }

  SearchReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SearchReply& from);
  void MergeFrom(const SearchReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SearchReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes ind = 1;
  void clear_ind();
  static const int kIndFieldNumber = 1;
  const ::std::string& ind() const;
  void set_ind(const ::std::string& value);
  #if LANG_CXX11
  void set_ind(::std::string&& value);
  #endif
  void set_ind(const char* value);
  void set_ind(const void* value, size_t size);
  ::std::string* mutable_ind();
  ::std::string* release_ind();
  void set_allocated_ind(::std::string* ind);

  // @@protoc_insertion_point(class_scope:DistSSE.SearchReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ind_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CacheRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.CacheRequestMessage) */ {
 public:
  CacheRequestMessage();
  virtual ~CacheRequestMessage();

  CacheRequestMessage(const CacheRequestMessage& from);

  inline CacheRequestMessage& operator=(const CacheRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CacheRequestMessage& default_instance();

  static inline const CacheRequestMessage* internal_default_instance() {
    return reinterpret_cast<const CacheRequestMessage*>(
               &_CacheRequestMessage_default_instance_);
  }

  void Swap(CacheRequestMessage* other);

  // implements Message ----------------------------------------------

  inline CacheRequestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  CacheRequestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CacheRequestMessage& from);
  void MergeFrom(const CacheRequestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CacheRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes tw = 1;
  void clear_tw();
  static const int kTwFieldNumber = 1;
  const ::std::string& tw() const;
  void set_tw(const ::std::string& value);
  #if LANG_CXX11
  void set_tw(::std::string&& value);
  #endif
  void set_tw(const char* value);
  void set_tw(const void* value, size_t size);
  ::std::string* mutable_tw();
  ::std::string* release_tw();
  void set_allocated_tw(::std::string* tw);

  // bytes inds = 2;
  void clear_inds();
  static const int kIndsFieldNumber = 2;
  const ::std::string& inds() const;
  void set_inds(const ::std::string& value);
  #if LANG_CXX11
  void set_inds(::std::string&& value);
  #endif
  void set_inds(const char* value);
  void set_inds(const void* value, size_t size);
  ::std::string* mutable_inds();
  ::std::string* release_inds();
  void set_allocated_inds(::std::string* inds);

  // @@protoc_insertion_point(class_scope:DistSSE.CacheRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr tw_;
  ::google::protobuf::internal::ArenaStringPtr inds_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UpdateRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.UpdateRequestMessage) */ {
 public:
  UpdateRequestMessage();
  virtual ~UpdateRequestMessage();

  UpdateRequestMessage(const UpdateRequestMessage& from);

  inline UpdateRequestMessage& operator=(const UpdateRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateRequestMessage& default_instance();

  static inline const UpdateRequestMessage* internal_default_instance() {
    return reinterpret_cast<const UpdateRequestMessage*>(
               &_UpdateRequestMessage_default_instance_);
  }

  void Swap(UpdateRequestMessage* other);

  // implements Message ----------------------------------------------

  inline UpdateRequestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  UpdateRequestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UpdateRequestMessage& from);
  void MergeFrom(const UpdateRequestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UpdateRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes l = 1;
  void clear_l();
  static const int kLFieldNumber = 1;
  const ::std::string& l() const;
  void set_l(const ::std::string& value);
  #if LANG_CXX11
  void set_l(::std::string&& value);
  #endif
  void set_l(const char* value);
  void set_l(const void* value, size_t size);
  ::std::string* mutable_l();
  ::std::string* release_l();
  void set_allocated_l(::std::string* l);

  // bytes e = 2;
  void clear_e();
  static const int kEFieldNumber = 2;
  const ::std::string& e() const;
  void set_e(const ::std::string& value);
  #if LANG_CXX11
  void set_e(::std::string&& value);
  #endif
  void set_e(const char* value);
  void set_e(const void* value, size_t size);
  ::std::string* mutable_e();
  ::std::string* release_e();
  void set_allocated_e(::std::string* e);

  // uint64 counter = 3;
  void clear_counter();
  static const int kCounterFieldNumber = 3;
  ::google::protobuf::uint64 counter() const;
  void set_counter(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:DistSSE.UpdateRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr l_;
  ::google::protobuf::internal::ArenaStringPtr e_;
  ::google::protobuf::uint64 counter_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ExecuteStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DistSSE.ExecuteStatus) */ {
 public:
  ExecuteStatus();
  virtual ~ExecuteStatus();

  ExecuteStatus(const ExecuteStatus& from);

  inline ExecuteStatus& operator=(const ExecuteStatus& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExecuteStatus& default_instance();

  static inline const ExecuteStatus* internal_default_instance() {
    return reinterpret_cast<const ExecuteStatus*>(
               &_ExecuteStatus_default_instance_);
  }

  void Swap(ExecuteStatus* other);

  // implements Message ----------------------------------------------

  inline ExecuteStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  ExecuteStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ExecuteStatus& from);
  void MergeFrom(const ExecuteStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ExecuteStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  bool status() const;
  void set_status(bool value);

  // @@protoc_insertion_point(class_scope:DistSSE.ExecuteStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool status_;
  mutable int _cached_size_;
  friend struct  protobuf_DistSSE_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SetupRequestMessage

// uint64 setup_size = 1;
inline void SetupRequestMessage::clear_setup_size() {
  setup_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SetupRequestMessage::setup_size() const {
  // @@protoc_insertion_point(field_get:DistSSE.SetupRequestMessage.setup_size)
  return setup_size_;
}
inline void SetupRequestMessage::set_setup_size(::google::protobuf::uint64 value) {
  
  setup_size_ = value;
  // @@protoc_insertion_point(field_set:DistSSE.SetupRequestMessage.setup_size)
}

// -------------------------------------------------------------------

// SearchRequestMessage

// bytes kw = 1;
inline void SearchRequestMessage::clear_kw() {
  kw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SearchRequestMessage::kw() const {
  // @@protoc_insertion_point(field_get:DistSSE.SearchRequestMessage.kw)
  return kw_.GetNoArena();
}
inline void SearchRequestMessage::set_kw(const ::std::string& value) {
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.SearchRequestMessage.kw)
}
#if LANG_CXX11
inline void SearchRequestMessage::set_kw(::std::string&& value) {
  
  kw_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.SearchRequestMessage.kw)
}
#endif
inline void SearchRequestMessage::set_kw(const char* value) {
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.SearchRequestMessage.kw)
}
inline void SearchRequestMessage::set_kw(const void* value, size_t size) {
  
  kw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.SearchRequestMessage.kw)
}
inline ::std::string* SearchRequestMessage::mutable_kw() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.SearchRequestMessage.kw)
  return kw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SearchRequestMessage::release_kw() {
  // @@protoc_insertion_point(field_release:DistSSE.SearchRequestMessage.kw)
  
  return kw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SearchRequestMessage::set_allocated_kw(::std::string* kw) {
  if (kw != NULL) {
    
  } else {
    
  }
  kw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), kw);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.SearchRequestMessage.kw)
}

// bytes tw = 2;
inline void SearchRequestMessage::clear_tw() {
  tw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SearchRequestMessage::tw() const {
  // @@protoc_insertion_point(field_get:DistSSE.SearchRequestMessage.tw)
  return tw_.GetNoArena();
}
inline void SearchRequestMessage::set_tw(const ::std::string& value) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.SearchRequestMessage.tw)
}
#if LANG_CXX11
inline void SearchRequestMessage::set_tw(::std::string&& value) {
  
  tw_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.SearchRequestMessage.tw)
}
#endif
inline void SearchRequestMessage::set_tw(const char* value) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.SearchRequestMessage.tw)
}
inline void SearchRequestMessage::set_tw(const void* value, size_t size) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.SearchRequestMessage.tw)
}
inline ::std::string* SearchRequestMessage::mutable_tw() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.SearchRequestMessage.tw)
  return tw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SearchRequestMessage::release_tw() {
  // @@protoc_insertion_point(field_release:DistSSE.SearchRequestMessage.tw)
  
  return tw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SearchRequestMessage::set_allocated_tw(::std::string* tw) {
  if (tw != NULL) {
    
  } else {
    
  }
  tw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tw);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.SearchRequestMessage.tw)
}

// uint64 uc = 3;
inline void SearchRequestMessage::clear_uc() {
  uc_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SearchRequestMessage::uc() const {
  // @@protoc_insertion_point(field_get:DistSSE.SearchRequestMessage.uc)
  return uc_;
}
inline void SearchRequestMessage::set_uc(::google::protobuf::uint64 value) {
  
  uc_ = value;
  // @@protoc_insertion_point(field_set:DistSSE.SearchRequestMessage.uc)
}

// -------------------------------------------------------------------

// SearchReply

// bytes ind = 1;
inline void SearchReply::clear_ind() {
  ind_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SearchReply::ind() const {
  // @@protoc_insertion_point(field_get:DistSSE.SearchReply.ind)
  return ind_.GetNoArena();
}
inline void SearchReply::set_ind(const ::std::string& value) {
  
  ind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.SearchReply.ind)
}
#if LANG_CXX11
inline void SearchReply::set_ind(::std::string&& value) {
  
  ind_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.SearchReply.ind)
}
#endif
inline void SearchReply::set_ind(const char* value) {
  
  ind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.SearchReply.ind)
}
inline void SearchReply::set_ind(const void* value, size_t size) {
  
  ind_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.SearchReply.ind)
}
inline ::std::string* SearchReply::mutable_ind() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.SearchReply.ind)
  return ind_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SearchReply::release_ind() {
  // @@protoc_insertion_point(field_release:DistSSE.SearchReply.ind)
  
  return ind_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SearchReply::set_allocated_ind(::std::string* ind) {
  if (ind != NULL) {
    
  } else {
    
  }
  ind_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ind);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.SearchReply.ind)
}

// -------------------------------------------------------------------

// CacheRequestMessage

// bytes tw = 1;
inline void CacheRequestMessage::clear_tw() {
  tw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CacheRequestMessage::tw() const {
  // @@protoc_insertion_point(field_get:DistSSE.CacheRequestMessage.tw)
  return tw_.GetNoArena();
}
inline void CacheRequestMessage::set_tw(const ::std::string& value) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.CacheRequestMessage.tw)
}
#if LANG_CXX11
inline void CacheRequestMessage::set_tw(::std::string&& value) {
  
  tw_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.CacheRequestMessage.tw)
}
#endif
inline void CacheRequestMessage::set_tw(const char* value) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.CacheRequestMessage.tw)
}
inline void CacheRequestMessage::set_tw(const void* value, size_t size) {
  
  tw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.CacheRequestMessage.tw)
}
inline ::std::string* CacheRequestMessage::mutable_tw() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.CacheRequestMessage.tw)
  return tw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CacheRequestMessage::release_tw() {
  // @@protoc_insertion_point(field_release:DistSSE.CacheRequestMessage.tw)
  
  return tw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CacheRequestMessage::set_allocated_tw(::std::string* tw) {
  if (tw != NULL) {
    
  } else {
    
  }
  tw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tw);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.CacheRequestMessage.tw)
}

// bytes inds = 2;
inline void CacheRequestMessage::clear_inds() {
  inds_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CacheRequestMessage::inds() const {
  // @@protoc_insertion_point(field_get:DistSSE.CacheRequestMessage.inds)
  return inds_.GetNoArena();
}
inline void CacheRequestMessage::set_inds(const ::std::string& value) {
  
  inds_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.CacheRequestMessage.inds)
}
#if LANG_CXX11
inline void CacheRequestMessage::set_inds(::std::string&& value) {
  
  inds_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.CacheRequestMessage.inds)
}
#endif
inline void CacheRequestMessage::set_inds(const char* value) {
  
  inds_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.CacheRequestMessage.inds)
}
inline void CacheRequestMessage::set_inds(const void* value, size_t size) {
  
  inds_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.CacheRequestMessage.inds)
}
inline ::std::string* CacheRequestMessage::mutable_inds() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.CacheRequestMessage.inds)
  return inds_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CacheRequestMessage::release_inds() {
  // @@protoc_insertion_point(field_release:DistSSE.CacheRequestMessage.inds)
  
  return inds_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CacheRequestMessage::set_allocated_inds(::std::string* inds) {
  if (inds != NULL) {
    
  } else {
    
  }
  inds_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), inds);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.CacheRequestMessage.inds)
}

// -------------------------------------------------------------------

// UpdateRequestMessage

// bytes l = 1;
inline void UpdateRequestMessage::clear_l() {
  l_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UpdateRequestMessage::l() const {
  // @@protoc_insertion_point(field_get:DistSSE.UpdateRequestMessage.l)
  return l_.GetNoArena();
}
inline void UpdateRequestMessage::set_l(const ::std::string& value) {
  
  l_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.UpdateRequestMessage.l)
}
#if LANG_CXX11
inline void UpdateRequestMessage::set_l(::std::string&& value) {
  
  l_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.UpdateRequestMessage.l)
}
#endif
inline void UpdateRequestMessage::set_l(const char* value) {
  
  l_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.UpdateRequestMessage.l)
}
inline void UpdateRequestMessage::set_l(const void* value, size_t size) {
  
  l_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.UpdateRequestMessage.l)
}
inline ::std::string* UpdateRequestMessage::mutable_l() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.UpdateRequestMessage.l)
  return l_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateRequestMessage::release_l() {
  // @@protoc_insertion_point(field_release:DistSSE.UpdateRequestMessage.l)
  
  return l_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateRequestMessage::set_allocated_l(::std::string* l) {
  if (l != NULL) {
    
  } else {
    
  }
  l_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), l);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.UpdateRequestMessage.l)
}

// bytes e = 2;
inline void UpdateRequestMessage::clear_e() {
  e_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UpdateRequestMessage::e() const {
  // @@protoc_insertion_point(field_get:DistSSE.UpdateRequestMessage.e)
  return e_.GetNoArena();
}
inline void UpdateRequestMessage::set_e(const ::std::string& value) {
  
  e_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DistSSE.UpdateRequestMessage.e)
}
#if LANG_CXX11
inline void UpdateRequestMessage::set_e(::std::string&& value) {
  
  e_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DistSSE.UpdateRequestMessage.e)
}
#endif
inline void UpdateRequestMessage::set_e(const char* value) {
  
  e_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DistSSE.UpdateRequestMessage.e)
}
inline void UpdateRequestMessage::set_e(const void* value, size_t size) {
  
  e_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DistSSE.UpdateRequestMessage.e)
}
inline ::std::string* UpdateRequestMessage::mutable_e() {
  
  // @@protoc_insertion_point(field_mutable:DistSSE.UpdateRequestMessage.e)
  return e_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateRequestMessage::release_e() {
  // @@protoc_insertion_point(field_release:DistSSE.UpdateRequestMessage.e)
  
  return e_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateRequestMessage::set_allocated_e(::std::string* e) {
  if (e != NULL) {
    
  } else {
    
  }
  e_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), e);
  // @@protoc_insertion_point(field_set_allocated:DistSSE.UpdateRequestMessage.e)
}

// uint64 counter = 3;
inline void UpdateRequestMessage::clear_counter() {
  counter_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UpdateRequestMessage::counter() const {
  // @@protoc_insertion_point(field_get:DistSSE.UpdateRequestMessage.counter)
  return counter_;
}
inline void UpdateRequestMessage::set_counter(::google::protobuf::uint64 value) {
  
  counter_ = value;
  // @@protoc_insertion_point(field_set:DistSSE.UpdateRequestMessage.counter)
}

// -------------------------------------------------------------------

// ExecuteStatus

// bool status = 1;
inline void ExecuteStatus::clear_status() {
  status_ = false;
}
inline bool ExecuteStatus::status() const {
  // @@protoc_insertion_point(field_get:DistSSE.ExecuteStatus.status)
  return status_;
}
inline void ExecuteStatus::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:DistSSE.ExecuteStatus.status)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace DistSSE

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DistSSE_2eproto__INCLUDED
